In [1]:
pip install --upgrade comtradeapicall

Requirement already satisfied: comtradeapicall in c:\users\carlo\anaconda3\lib\site-packages (1.2.1)Note: you may need to restart the kernel to use updated packages.

In [1]:
import requests
from bs4 import BeautifulSoup
import comtradeapicall
import pandas as pd
import sys

In [2]:
country_code = pd.read_excel("country_code.xlsx")

In [3]:
country_code["text"].unique()

array(['Afghanistan', 'Africa CAMEU region, nes', 'Åland Islands ',
       'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola',
       'Anguilla', 'Antarctica', 'Antigua and Barbuda',
       'Arab Rep. of Yemen (...1990)', 'Areas, nes', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belgium-Luxembourg (...1998)', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia (Plurinational State of)', 'Bonaire',
       'Bosnia Herzegovina', 'Botswana', 'Bouvet Island',
       'Br. Antarctic Terr.', 'Br. Indian Ocean Terr.', 'Br. Virgin Isds',
       'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Bunkers',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'CACM, nes', 'Cambodia',
       'Cameroon', 'Canada', 'Caribbean, nes', 'Cayman Isds',
       'Central African Rep.', 'Chad', 'Channel Islands ', 'Chile',
       'China', 'China, Hong Kong SAR', 'China, Macao SAR',
       'Christmas Isds', 'Cocos Isds', 'Colombia', 'Comoros', 'Congo',
       'Cook Isds', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba',
       'Curaçao', 'Cyprus', 'Czechia', 'Czechoslovakia (...1992)',
       "Dem. People's Rep. of Korea", 'Dem. Rep. of Germany (...1990)',
       'Dem. Rep. of the Congo', 'Dem. Rep. of Vietnam (...1974)',
       'Dem. Yemen (...1990)', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Rep.', 'East and West Pakistan (...1971)',
       'Eastern Europe, nes', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Ethiopia (...1992)', 'Europe EFTA, nes', 'Europe EU, nes',
       'Faeroe Isds', 'Falkland Isds (Malvinas)',
       'Fed. Rep. of Germany (...1990)', 'Fiji', 'Finland',
       'Fr. South Antarctic Terr.', 'France', 'Free Zones',
       'French Guiana (Overseas France)', 'French Polynesia',
       'FS Micronesia', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe (Overseas France)', 'Guam', 'Guatemala', 'Guernsey',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Heard Island and McDonald Islands',
       'Holy See (Vatican City State)', 'Honduras', 'Hungary', 'Iceland',
       'India', 'India (...1974)', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Isle of Man ', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'LAIA, nes', "Lao People's Dem. Rep.", 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein ',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Marshall Isds',
       'Martinique (Overseas France)', 'Mauritania', 'Mauritius',
       'Mayotte (Overseas France)', 'Metropolitan France', 'Mexico',
       'Midway Islands', 'Mongolia', 'Montenegro', 'Montserrat',
       'Morocco', 'Mozambique', 'Myanmar', 'N. Mariana Isds', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles (...2010)',
       'Netherlands Antilles and Aruba (...1985)', 'Neutral Zone',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'Norfolk Isds', 'North America and Central America, nes',
       'North Macedonia', 'Northern Africa, nes', 'Norway',
       'Norway, excluding Svalbard and Jan Mayen', 'Oceania, nes', 'Oman',
       'Other Africa, nes', 'Other Asia, nes', 'Other Europe, nes',
       'Pacific Isds (...1991)', 'Pakistan', 'Palau', 'Panama',
       'Panama, excl.Canal Zone (...1977)', 'Panama-Canal-Zone (...1977)',
       'Papua New Guinea', 'Paraguay', 'Peninsula Malaysia (...1963)',
       'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal',
       'Puerto Rico ', 'Qatar', 'Rep. of Korea', 'Rep. of Moldova',
       'Rep. of Vietnam (...1974)', 'Rest of America, nes',
       'Réunion (Overseas France)', 'Rhodesia Nyas (...1964)', 'Romania',
       'Russian Federation', 'Rwanda', 'Ryukyu Isd', 'Sabah (...1963)',
       'Saint Barthélemy', 'Saint Helena', 'Saint Kitts and Nevis',
       'Saint Kitts, Nevis and Anguilla (...1980)', 'Saint Lucia',
       'Saint Maarten', 'Saint Martin (French part) ',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Sarawak',
       'Saudi Arabia', 'Senegal', 'Serbia',
       'Serbia and Montenegro (...2005)', 'Seychelles', 'Sierra Leone',
       'Sikkim, Protectorate of India (...1974)', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Isds', 'Somalia', 'South Africa',
       'South Georgia and the South Sandwich Islands', 'South Sudan',
       'Southern African Customs Union (...1999)', 'Spain',
       'Special Categories', 'Sri Lanka', 'State of Palestine', 'Sudan',
       'Sudan (...2011)', 'Suriname', 'Svalbard and Jan Mayen Islands ',
       'Sweden', 'Switzerland ', 'Switzerland', 'Syria',
       'Taiwan, Province of China', 'Tajikistan', 'Tanganyika (...1964)',
       'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Türkiye', 'Turkmenistan',
       'Turks and Caicos Isds', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom',
       'United Rep. of Tanzania', 'United States Minor Outlying Islands',
       'United States of America', 'Uruguay', 'US Misc. Pacific Isds',
       'US Virgin Isds (...1980)', 'USA', 'USA and Puerto Rico (...1980)',
       'USSR (...1990)', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Viet Nam',
       'Wake Island', 'Wallis and Futuna Isds', 'Western Asia, nes',
       'Western Sahara', 'World', 'Yemen', 'Yugoslavia (...1991)',
       'Zambia', 'Zanzibar and Pemba Isd (...1964)', 'Zimbabwe'],
      dtype=object)

In [4]:
codes=[]
countries = ['Italy', 'France', 'Spain', 'Germany', 'Portugal', 'Romania',
       'Greece', 'Russia', 'Moldova', 'Hungary', 'Bulgaria',
       'Serbia And Montenegro', 'Ukraine', 'Serbia', 'Croatia', 'Austria',
       'Republic of North Macedonia', 'Albania', 'Switzerland',
       'Slovenia', 'Cyprus', 'Czech Republic', 'Slovakia',
       'Bosnia and Herzegovina', 'Montenegro', 'Belarus', 'Luxemburg',
       'Malta', 'Belgium', 'Netherlands', 'Estonia', 'United Kingdom',
       'Sweden', 'Lithuania', 'Latvia', 'Denmark', 'Poland', 'Andorra',
       'Belgium and Luxemburg', 'Faroe Islands', 'Finland', 'Ireland',
       'Liechtenstein', 'Monaco', 'Norway', 'San Marino', 'Iceland']
for country in countries:
    codes.extend(country_code.query(f"text==\"{country}\"")["id"])

In [5]:
codes

[380,
 251,
 724,
 276,
 620,
 642,
 300,
 348,
 100,
 804,
 688,
 191,
 40,
 8,
 757,
 705,
 196,
 703,
 499,
 112,
 470,
 56,
 528,
 233,
 826,
 752,
 440,
 428,
 208,
 616,
 20,
 246,
 372,
 579,
 674,
 352]

In [14]:
def get_countrycode(row):
    
    countries = ['Italy', 'France', 'Spain', 'Germany', 'Portugal', 'Romania',
       'Greece', 'Russia', 'Moldova', 'Hungary', 'Bulgaria',
       'Serbia And Montenegro', 'Ukraine', 'Serbia', 'Croatia', 'Austria',
       'Republic of North Macedonia', 'Albania', 'Switzerland',
       'Slovenia', 'Cyprus', 'Czech Republic', 'Slovakia',
       'Bosnia and Herzegovina', 'Montenegro', 'Belarus', 'Luxemburg',
       'Malta', 'Belgium', 'Netherlands', 'Estonia', 'United Kingdom',
       'Sweden', 'Lithuania', 'Latvia', 'Denmark', 'Poland', 'Andorra',
       'Belgium and Luxemburg', 'Faroe Islands', 'Finland', 'Ireland',
       'Liechtenstein', 'Monaco', 'Norway', 'San Marino', 'Iceland']
    for country in countries:
        if row["text"] in countries:
            print(row["id"])

In [15]:
country_code.apply(get_countrycode)

KeyError: 'text'

In [13]:
country_code.iloc[0]["text"] in countries

False

In [12]:
country_code.head()

,id,text,PartnerCode,PartnerDesc,partnerNote,PartnerCodeIsoAlpha2,PartnerCodeIsoAlpha3,entryEffectiveDate,isGroup,entryExpiredDate
0,4,Afghanistan,4,Afghanistan,Afghanistan,AF,AFG,1900-01-01T00:00:00,False,NaN
1,472,"Africa CAMEU region, nes",472,"Africa CAMEU region, nes","Africa CAMEU region, not elsewhere specified",NaN,_AC,1900-01-01T00:00:00,False,NaN
2,248,Åland Islands,248,Åland Islands,NaN,AX,ALA,1900-01-01T00:00:00,False,NaN
3,8,Albania,8,Albania,Albania,AL,ALB,1900-01-01T00:00:00,False,NaN
4,12,Algeria,12,Algeria,Algeria,DZ,DZA,1900-01-01T00:00:00,False,NaN

In [11]:
country_code.apply(get_countrycode)

KeyError: 'text'

In [11]:
country_code

,id,text,PartnerCode,PartnerDesc,partnerNote,PartnerCodeIsoAlpha2,PartnerCodeIsoAlpha3,entryEffectiveDate,isGroup,entryExpiredDate
0,4,Afghanistan,4,Afghanistan,Afghanistan,AF,AFG,1900-01-01T00:00:00,False,NaN
1,472,"Africa CAMEU region, nes",472,"Africa CAMEU region, nes","Africa CAMEU region, not elsewhere specified",NaN,_AC,1900-01-01T00:00:00,False,NaN
2,248,Åland Islands,248,Åland Islands,NaN,AX,ALA,1900-01-01T00:00:00,False,NaN
3,8,Albania,8,Albania,Albania,AL,ALB,1900-01-01T00:00:00,False,NaN
4,12,Algeria,12,Algeria,Algeria,DZ,DZA,1900-01-01T00:00:00,False,NaN
...,...,...,...,...,...,...,...,...,...,...
305,887,Yemen,887,Yemen,Yemen,YE,YEM,1991-01-01T00:00:00,False,NaN
306,890,Yugoslavia (...1991),890,Yugoslavia (...1991),Former Yugoslavia,YU,YUG,1900-01-01T00:00:00,False,1991-12-31T00:00:00
307,894,Zambia,894,Zambia,Zambia,ZM,ZMB,1965-01-01T00:00:00,False,NaN
308,836,Zanzibar and Pemba Isd (...1964),836,Zanzibar and Pemba Isd (...1964),Former Zanzibar and Pemba Island,NaN,_ZP,1900-01-01T00:00:00,False,1964-12-31T00:00:00
309,716,Zimbabwe,716,Zimbabwe,Zimbabwe,ZW,ZWE,1965-01-01T00:00:00,False,NaN

In [10]:
mydf2 = comtradeapicall.previewTarifflineData(typeCode='C', freqCode='X', clCode="HS", period='202201',
                                             reporterCode='76', cmdCode="2204", flowCode='X', partnerCode="650",
                                             partner2Code=None,
                                             customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                             countOnly=None, includeDesc=True)

{"elapsedTime":"0 secs","count":-1,"data":[],"error":"Invalid parameter value","errorObject":[{"memberNames":["freqCode"],"errorMessage":"The field freqCode is invalid"}]}

In [15]:
mydf = comtradeapicall.previewTarifflineData(typeCode='C', freqCode='M', clCode='HS', period='202201',
                                             reporterCode='620', cmdCode="2204", flowCode='M', partnerCode="76",
                                             partner2Code=None,
                                             customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                             countOnly=None, includeDesc=True)

In [ ]:
mydf.columns

Index(['typeCode', 'freqCode', 'refPeriodId', 'period', 'reporterCode',
       'reporterDesc', 'reporterISO', 'flowCode', 'flowDesc', 'partnerCode',
       'partnerDesc', 'partnerISO', 'partner2Code', 'partner2Desc',
       'partner2ISO', 'classificationCode', 'cmdCode', 'cmdDesc',
       'customsCode', 'customsDesc', 'mosCode', 'motCode', 'motDesc',
       'qtyUnitCode', 'qtyUnitAbbr', 'qty', 'altQtyUnitCode', 'altQtyUnitAbbr',
       'altQty', 'netWgt', 'grossWgt', 'cifvalue', 'fobvalue', 'primaryValue'],
      dtype='object')

In [ ]:
mydf.drop(["typeCode","freqCode","refPeriodId","reporterCode",'reporterISO',"flowCode",'partnerCode','partnerISO','partner2Code', 'partner2Desc',
       'partner2ISO','classificationCode','altQtyUnitAbbr','qtyUnitCode','mosCode','motCode','altQtyUnitCode', 'altQtyUnitAbbr', 'grossWgt',
       'altQty','fobvalue' ], axis=1)

,period,reporterDesc,flowDesc,partnerDesc,cmdCode,cmdDesc,customsCode,customsDesc,motDesc,qtyUnitAbbr,qty,netWgt,cifvalue,primaryValue
0,202201,Portugal,Import,Brazil,22042197,None,C20,CPC N.E.S.,Air,l,5.0,5.0,101.830285,101.830285
1,202201,Portugal,Import,Brazil,22042132,None,C01,Clearance for home use,Sea,l,27.0,27.0,409.584035,409.584035
2,202201,Portugal,Import,Brazil,22041098,None,C01,Clearance for home use,Sea,l,36.0,36.0,586.089862,586.089862
3,202201,Portugal,Import,Brazil,22042169,None,C01,Clearance for home use,Sea,l,230.0,230.0,2200.665601,2200.665601
4,202201,Portugal,Import,Brazil,22042178,None,C01,Clearance for home use,Sea,l,18.0,18.0,240.998341,240.998341
5,202201,Portugal,Import,Brazil,22042138,None,C01,Clearance for home use,Sea,l,72.0,72.0,566.855253,566.855253
6,202201,Portugal,Import,Brazil,22042189,None,C01,Clearance for home use,Air,l,1.0,1.0,4.525790,4.525790
7,202201,Portugal,Import,Brazil,22042109,None,C20,CPC N.E.S.,Air,l,0.0,0.0,24.891847,24.891847

In [ ]:
# The Cost, Insurance, and Freight (CIF) value of a product is an important figure used by customs authorities to calculate duties and taxes. It represents the total cost of the goods including their transportation costs from the place of origin to their destination.
#The FOB (Free On Board) price is the price of goods at the frontier of the exporting country or price of a service provided to a non-resident. It includes the values of the goods or services at the basic price, the transport and distribution services up to the frontier, the taxes minus the subsidies
# Primary value refers to the purpose for which the item was created, while secondary value refers to an additional value that the participants can perceive the item to hold, such as a perception that an item can represent one's identity.

In [ ]:
mydf["cmdDesc"].unique()

array([None], dtype=object)

In [ ]:
mydf

,typeCode,freqCode,refPeriodId,period,reporterCode,reporterDesc,reporterISO,flowCode,flowDesc,partnerCode,...,qtyUnitAbbr,qty,altQtyUnitCode,altQtyUnitAbbr,altQty,netWgt,grossWgt,cifvalue,fobvalue,primaryValue
0,C,M,20220101,202201,620,Portugal,PRT,M,Import,76,...,l,5.0,7,l,5.0,5.0,0.0,101.830285,0.0,101.830285
1,C,M,20220101,202201,620,Portugal,PRT,M,Import,76,...,l,27.0,7,l,27.0,27.0,0.0,409.584035,0.0,409.584035
2,C,M,20220101,202201,620,Portugal,PRT,M,Import,76,...,l,36.0,7,l,36.0,36.0,0.0,586.089862,0.0,586.089862
3,C,M,20220101,202201,620,Portugal,PRT,M,Import,76,...,l,230.0,7,l,230.0,230.0,0.0,2200.665601,0.0,2200.665601
4,C,M,20220101,202201,620,Portugal,PRT,M,Import,76,...,l,18.0,7,l,18.0,18.0,0.0,240.998341,0.0,240.998341
5,C,M,20220101,202201,620,Portugal,PRT,M,Import,76,...,l,72.0,7,l,72.0,72.0,0.0,566.855253,0.0,566.855253
6,C,M,20220101,202201,620,Portugal,PRT,M,Import,76,...,l,1.0,7,l,1.0,1.0,0.0,4.525790,0.0,4.525790
7,C,M,20220101,202201,620,Portugal,PRT,M,Import,76,...,l,0.0,7,l,0.0,0.0,0.0,24.891847,0.0,24.891847

In [ ]:
new_df = comtradeapicall.previewFinalData(typeCode='C', freqCode='A', clCode='HS', period='2022',
                                        reporterCode="12", cmdCode='220410', flowCode='X', partnerCode="0",
                                        partner2Code=None,
                                        customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                        aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

new_df = new_df.drop(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth',
       'reporterCode', 'reporterISO','flowCode', 'partnerISO','partner2Code',
       'partner2ISO', 'partner2Desc','classificationCode', 'classificationSearchCode', 'isOriginalClassification','cmdCode', 'aggrLevel', 'isLeaf', 'customsCode','customsDesc',
       'mosCode', 'motCode', 'motDesc','qtyUnitCode','isAltQtyEstimated','isNetWgtEstimated','legacyEstimationFlag', 'isReported', 'isAggregate','altQtyUnitAbbr', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty','cmdDesc','grossWgt','isGrossWgtEstimated','isQtyEstimated',  ], axis=1)
country_export = pd.concat([country_export, new_df], axis=0).reset_index(drop=True)

KeyError: "['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth', 'reporterCode', 'reporterISO', 'flowCode', 'partnerISO', 'partner2Code', 'partner2ISO', 'partner2Desc', 'classificationCode', 'classificationSearchCode', 'isOriginalClassification', 'cmdCode', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc', 'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'isAltQtyEstimated', 'isNetWgtEstimated', 'legacyEstimationFlag', 'isReported', 'isAggregate', 'altQtyUnitAbbr', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty', 'cmdDesc', 'grossWgt', 'isGrossWgtEstimated', 'isQtyEstimated'] not found in axis"

In [ ]:
country_import = comtradeapicall.previewFinalData(typeCode='C', freqCode='A', clCode='HS', period='2022',
                                        reporterCode=f"{country}", cmdCode='2204', flowCode='M', partnerCode=0,
                                        partner2Code=None,
                                        customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                        aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

In [16]:
codes

[380,
 251,
 724,
 276,
 620,
 642,
 300,
 348,
 100,
 804,
 688,
 191,
 40,
 8,
 757,
 705,
 196,
 703,
 499,
 112,
 470,
 56,
 528,
 233,
 826,
 752,
 440,
 428,
 208,
 616,
 20,
 246,
 372,
 579,
 674,
 352]

In [1]:
for country in codes:
    new_df = comtradeapicall.previewFinalData(typeCode='C', freqCode='A', clCode='HS', period='2022',
                                        reporterCode=f"{country}", cmdCode='2204', flowCode='M', partnerCode=0,
                                        partner2Code=None,
                                        customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                        aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

    country_import = pd.concat([country_import, new_df], axis=0).reset_index(drop=True)
country_import = country_import.drop(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth',
       'reporterCode', 'reporterISO','flowCode', 'partnerISO','partner2Code',
       'partner2ISO', 'partner2Desc','classificationCode', 'classificationSearchCode', 'isOriginalClassification','cmdCode', 'aggrLevel', 'isLeaf', 'customsCode','customsDesc',
       'mosCode', 'motCode', 'motDesc','qtyUnitCode','isAltQtyEstimated','isNetWgtEstimated','legacyEstimationFlag', 'isReported', 'isAggregate','altQtyUnitAbbr', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty','cmdDesc','grossWgt','isGrossWgtEstimated','isQtyEstimated',  ], axis=1)

NameError: name 'codes' is not defined

In [ ]:
for country in codes:
    new_df = comtradeapicall.previewFinalData(typeCode='C', freqCode='A', clCode='HS', period='2022',
                                        reporterCode=f"{country}", cmdCode='2204', flowCode='X', partnerCode=0,
                                        partner2Code=None,
                                        customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                        aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

    country_export = pd.concat([country_export, new_df], axis=0).reset_index(drop=True)
country_export = country_export.drop(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth',
       'reporterCode', 'reporterISO','flowCode', 'partnerISO','partner2Code',
       'partner2ISO', 'partner2Desc','classificationCode', 'classificationSearchCode', 'isOriginalClassification','cmdCode', 'aggrLevel', 'isLeaf', 'customsCode','customsDesc',
       'mosCode', 'motCode', 'motDesc','qtyUnitCode','isAltQtyEstimated','isNetWgtEstimated','legacyEstimationFlag', 'isReported', 'isAggregate','altQtyUnitAbbr', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty','cmdDesc','grossWgt','isGrossWgtEstimated','isQtyEstimated',  ], axis=1)

In [2]:
country_import

NameError: name 'country_import' is not defined

In [3]:
country_export

NameError: name 'country_export' is not defined

In [ ]:
mydf3 = comtradeapicall.previewFinalData(typeCode='C', freqCode='M', clCode='HS', period='202312',
                                        reporterCode='32', cmdCode='220410', flowCode='X', partnerCode=0,
                                        partner2Code=None,
                                        customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                        aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

In [ ]:
mydf3["partnerDesc"].unique()

array(['World'], dtype=object)

In [7]:
country_export = mydf3.drop(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth',
       'reporterCode', 'reporterISO','flowCode', 'partnerISO','partner2Code',
       'partner2ISO', 'partner2Desc','classificationCode', 'classificationSearchCode', 'isOriginalClassification','cmdCode', 'aggrLevel', 'isLeaf', 'customsCode','customsDesc',
       'mosCode', 'motCode', 'motDesc','qtyUnitCode','isAltQtyEstimated','isNetWgtEstimated','legacyEstimationFlag', 'isReported', 'isAggregate','altQtyUnitAbbr', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty','cmdDesc','grossWgt','isGrossWgtEstimated','isQtyEstimated',  ], axis=1)

NameError: name 'mydf3' is not defined

In [ ]:
country_export

,period,reporterDesc,flowDesc,partnerCode,partnerDesc,qtyUnitAbbr,qty,netWgt,cifvalue,fobvalue,primaryValue
0,202312,Argentina,Export,0,World,l,242721.9,244115.9,None,1044511.14,1044511.14